[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "lerobot_policy_openvla_oft"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lerobot@git+https://github.com/huggingface/lerobot.git@507083249f9715b2ad3893fbe9757903055aa644",
    "timm>=1.0.27",
    "torch>=2.10.0",
    "transformers>=5.10.2",
]

[dependency-groups]
dev = [
    "mypy>=2.1.0",
    "pre-commit>=4.6.0",
    "pytest>=9.0.3",
    "ruff>=0.15.16",
]
